version: 0.2

phases:
  install:
    commands:
      - export PATH=$PATH:$(pwd)/vendor/tools/codebuild
      - export PATH=$PATH:$(pwd)/bin
  pre_build:
    commands:
      - |
        #
        # Run test.
        #
        set -eu;
        test;
  build:
    commands:
      - |
        #
        # Push to RubyGems.
        #
        set -eu;
        if trigger is release ?; then
          push-to-rubygems moca_rlibs;
        fi;
  post_build:
    commands:
      - |
        #
        # Notify the result.
        #
        set -eu;
        notify-release-gem moca_rlibs;
        notify-build-result moca_rlibs;
