version: 0.2

phases:
  install:
    commands:
      - export PATH=$PATH:$(pwd)/vendor/tools/codebuild
      - docker-login
  pre_build:
    commands:
      - |
        #
        # Run test.
        #
        set -eu;
        docker build -t mocaberos:mzk .;
        docker run --rm \
          -e CODECOV_TOKEN=$CODECOV_TOKEN \
          mocaberos:mzk \
          sh -c ./docker/scripts/test.sh;
  post_build:
    commands:
      - |
        #
        # Notify the result.
        #
        set -eu;
        notify-build-result moca_rlibs;
